version: 2
project_name: smartthings-go

# Library - no binaries to build
builds:
  - skip: true

# Generate changelog from commits
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

# GitHub release
release:
  github:
    owner: tj-smith47
    name: smartthings-go
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
